config/routes.rb
Rails.application.routes.draw do


  root "tweets#index"
  get "/user/login", to: "sessions#new"
  post "/user/login", to: "sessions#create"
  delete "/user/logout", to: "sessions#destroy"
  get "/user/signup", to: "sessions#entry"
  post "/user/signup", to: "sessions#setup"
  get "/tweet/new", to: "tweets#new", as:"tweet_new"
  post "/tweet/new", to: "tweets#create", as:"tweet_create"
  post "/comment", to:"comments#create"

  get "/userpage/:id", to: "relationships#account", as: "accountpage"
  post "/userpage/follow", to: "relationships#create"
  get "/commentpage/:id", to:"tweets#comments", as: "commentpage"

  post "/commentpage/:tweet_id", to:"comments#create"

  get "/relationship/followlist", to:"relationships#followlist"

  get "/api/good/:user_id/isgood/:tweet_id", to:"goods#index"
  get "/api/good/:user_id/good/:tweet_id", to:"goods#create"
  get "/api/good/:user_id/bad/:tweet_id", to:"goods#delete"


  resources :user, only:[:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only:[:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/feeling.rb
class Feeling < ApplicationRecord
    has_many :tweets
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :owners, class_name: "User", foreign_key: :owner_id
  belongs_to :followed, class_name: "User", foreign_key: :followed_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  belongs_to :feeling
  has_many :goods, dependent: :destroy


  validates :content, length:  {maximum:255}, presence: true
  validates :feeling_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :tweets
    has_many :owners, class_name: "Relationship", foreign_key: :owner_id
    has_many :followed, class_name: "Relationship", foreign_key: :followed_id
    has_many :following_user, through: :owners, source: :followed # 自分がフォローしている人
    has_many :follower_user, through: :followed, source: :owners # 自分をフォローしている人
    has_many :comments, dependent: :destroy
    has_many :goods, dependent: :destroy
    #インスタンスメソッドの定義
    def follow(user_id)
        #selfはオブジェクトそのものを取得している。->"user".follow
        owners.create(followed_id: user_id, owner_id: self.id)
    end

    def unfollow(user_id)
        owners.find_by(followed_id: user_id).destroy
    end

    def following?(user_id)
        owners.find_by(followed_id: user_id).present?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    private
    # ログイン済みユーザーかどうか確認
     def redirect_if_has_not_logged_in
       unless logged_in?
         redirect_to user_login_url
       end
     end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        comment = params[:session][:comment]
        tweet = Tweet.find(params[:tweet_id])
        
        comment = Comment.create(content: comment, user_id: current_user.id, tweet_id: tweet.id )

        if comment.save
            redirect_to request.referer
        end
    end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController

    def create
        if !Good.find_by(user_id: params[:user_id],tweet_id: params[:tweet_id])
            good = Good.new(user_id: current_user.id,tweet_id: params[:tweet_id])
            if good.save
                render json: {status:true}
            else
                render json: {status:false}
            end
        end

    end

    def delete
        if Good.find_by(user_id: params[:user_id],tweet_id: params[:tweet_id]).destroy
            render json: {status: true}
        else
            render json: {status: false}
        end

    end

    def index
        if Good.find_by(user_id: params[:user_id],tweet_id: params[:tweet_id])
            render json: {status: true}
        else
            render json: {status: false}
        end
    end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end
    def link
    end
    
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        current_user.follow(params[:user_id])
        redirect_to request.referer
    end
    def destroy
        current_user.unfollow(params[:user_id])
        redirect_to request.referer
    end

    def account
        @user = User.find(params[:id])
        @tweet = @user.tweets
    end
    
    def user_page
        @user = User.find(params[:id])
    end

    def followlist
        @follow = current_user.owners
        @follower = current_user.followed
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def entry
  end

  def create
    account=User.find_by(name: params[:session][:name])
    # hash値エラーが出るのは登録するときに、password_digestに直接入れているから
    # passwordとして登録すれば、勝手にpassword_digestに入る
    if account && account.authenticate(params[:session][:password])
      log_in account
      redirect_to root_url
    else
      render "new"
    end
  end

  def setup
    @account = User.new(name:params[:session][:name], password:params[:session][:password])
    if @account.save
      redirect_to root_url
    else
      render "entry"
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :redirect_if_has_not_logged_in
    

    def index
        @tweets = Tweet.all
    end

    def new
        @tweet = Tweet.new
        @feelings = Feeling.all
    end

    def create
        t = tweet_params
        tweet = Tweet.new(t)
        tweet.user_id = current_user.id
        if tweet.save
            redirect_to root_url
        else
            #flash[:notice] = ""
            #redirect_to
            #と同じ
            redirect_to tweet_new_url, notice: "正しく入力してください"
        end
    end
    
    def comments
        @tweet = Tweet.find(params[:id])
        @comment = Comment.where(tweet_id: params[:id])
    end

    private
    def tweet_params
        params.require(:session).permit(:content, :feeling_id)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:id] = user.id
    end
    def current_user
        if session[:id]
            @current_user ||= User.find(session[:id])
        end
    end
    def current_user?(user)
        user == current_user
    end
    def logged_in?
        !current_user.nil?
    end
    def log_out
        session.delete(:id)
        @current_user = nil
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hello/index.html.erb
Hello World!!
<%= link_to "ここを押してね", :controller => "hello", :action => "link" %>

app/views/hello/link.html.erb
Hello Word

app/views/relationships/account.html.erb
<h1><%= @user.name %></h1>
<div>
   <% if current_user != @user %>
   <% if current_user.following?(@user.id) %>
   <%= link_to 'フォロー外す', user_relationships_path(@user.id), method: :delete %>
   <% else %>
   <% if @user.following?(current_user.id) %>
   <%= link_to 'フォローバック', userpage_follow_path(user_id:@user.id), method: :post %>
   <% else %>
   <%= link_to 'フォローする', userpage_follow_path(user_id:@user.id), method: :post %>
   <% end %>
   <% end %>
   <% end %>
</div>

<h3>ツイート</h3>
<div>
   <% @tweet.each do |t|  %>
   <div>
      <%= t.content %>
      <%= link_to "コメントへ", commentpage_path(t.id) %>
   </div>
   <%end%>
</div>

app/views/relationships/followlist.html.erb
<h1><%= current_user.name %>さんのフォロー・フォロワー</h1>
<h3>フォロー一覧</h3>
<div>
    <% @follow.each do |t| %>
    <div>
        <%=t.followed.name %>
        <%= link_to "ツイートへ", accountpage_path(t.followed.id) %>
    </div>
    <%end%>
</div>
<h3>フォロワー一覧</h3>
<div>
    <% @follower.each do |t| %>
    <div>
        <%=t.owners.name %>
        <%= link_to "ツイートへ", accountpage_path(t.owners.id) %>

    </div>
    <%end%>
</div>

app/views/tweets/_logged_in.html.erb
<%= link_to "フォロー/フォロワー一覧", relationship_followlist_path %>

<h2>一覧</h2>
<%= link_to "投稿", tweet_new_path %>
<div>
    <% @tweets.each do |t| %>
        <div>
            <%= t.user.name %>(feel: <%= t.feeling.text %>) 
            <%= link_to "詳細へ", accountpage_path(t.user.id) %> 
            <%= t.content %> 
            <%= link_to "コメントへ", commentpage_path(t.id) %>
        </div>
    <% end %>
</div>
<%= link_to "ログアウト", user_logout_path, method: :delete %>

app/views/tweets/_not_logged_in.html.erb
<p>タスクの管理ができるアプリです。まずはログインをしてください。</p>
<%= link_to "ログイン", user_login_path%>
<p>未登録の場合は登録してください</p>
<%= link_to "登録", user_signup_path %>

app/views/tweets/comments.html.erb
<div>
    <h2><%= @tweet.user.name %></h2>
    <h1><%= @tweet.content %></h1>
    <h3><%= @tweet.created_at %></h3>
    <input type="hidden" id="user_id" value="<%= current_user.id%>" >
    <input type="hidden" id="tweet_id" value="<%= @tweet.id%>" >
    <button id="goodButton">♡</button>
    <%= javascript_pack_tag "good_action" %>
    <br>
    <br>
    <h2>コメント欄</h2>

    <div>
        <% @comment.each do |t| %>
        <div>
            <%= t.user.name%>: 
            <strong>
            <%= t.content%>
            </strong>
            <p>
            (<%= t.updated_at%>)
            </p>
        </div>
        <%end%>
    </div>

    <%= form_for(:session , url:commentpage_path(tweet_id: @tweet_id)) do |f| %>
        <%= f.label :コメント %>
        <%= f.text_field :comment %>
        <%= f.submit "コメントする" %>
    <% end %>
</div>

app/views/tweets/index.html.erb
<h1>Twitter</h1>
<% if logged_in? %>
    <%= render "tweets/logged_in" %>
<% else %>
    <%= render "tweets/not_logged_in" %>
<% end %>

app/views/tweets/main.html.erb
<h1>Twitter</h1>
<% if logged_in? %>
    <%= render "tweets/logged_in" %>
<% else %>
    <%= render "tweets/not_logged_in" %>
<% end %>

app/views/tweets/new.html.erb
<h1>投稿</h1>

<%= flash[:notice] %>

<%= form_for(:session , url:tweet_create_path) do |f| %>
    <%= f.label :投稿 %>
    <%= f.text_field :content %>
    <%= f.label :今の気持ちは？ %>
    <%= f.select :feeling_id, @feelings.map{|feeling| [feeling.text, feeling.id]}%>
    <%= f.submit "投稿" %>
<% end %>

app/views/tweets/newpost.html.erb
<h1>投稿</h1>
<%= form_for(:session , url:tweet_new_path) do |f| %>
    <%= f.label :投稿 %>
    <%= f.text_field :content %>
    <%= f.submit "投稿" %>
<% end %>